### ISSUE TITLE
ModuleNotFoundError: No module named 'ffrecord._ffrecord_cpp'

### ISSUE THREAD

**Issue by lk1983823** [HFAiLab/ffrecord#7]
After install ffrecord successfully, I have this problem when import ffrecord:
`ModuleNotFoundError: No module named 'ffrecord._ffrecord_cpp'`
Python 3.8
Ubuntu 18.04

Thanks.

**Comment by tuninger** [comment]
@lk1983823 ，请教下，您说的这个问题解决了么？我也遇到了同样的问题。

 Traceback (most recent call last):
  File "/root/ffrecord/a.py", line 1, in <module>
    from ffrecord import FileWriter
  File "/root/ffrecord/ffrecord/__init__.py", line 2, in <module>
    from .fileio import (
  File "/root/ffrecord/ffrecord/fileio.py", line 1, in <module>
    from ._ffrecord_cpp import (
ModuleNotFoundError: No module named 'ffrecord._ffrecord_cpp'
